title: Neotoma Community Stories
email: hoffmanick@gmail.com
description: "This website is a repository of stories contributed by members of Neotoma's community."
baseurl: "" # leave empty for user site
url: "https://neotomacommunity.github.io" # remove trailing slash

theme: minima
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Optional: add exclude list if you have large folders to ignore
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
